#!/bin/bash
# Just a bash script that might be useful for running your own hotspot.

#Initial wifi interface configuration
int=${1:-wlp0s18f2u5}
tunnel=${tunnel}
out=enp4s0

# Ideally make these persistent. Flshing ip tables is generally not a good thing
# if you have other software running on your box.
ip link set $int down
ip addr flush dev $int
ip link set $int up
ip addr add 10.0.0.1/24 dev $int

sleep 2

#Start dnsmasq
systemctl restart dnsmasq

# TODO set up openvpn
if [ -n "${tunnel}" ]; then
  # Start openvpn
  echo "Starting openvpn (left to reader)"
  out=tun0
else
  # Stop openvpn
  echo "Stopping openvpn (left to reader)"
fi

#Enable NAT
iptables --flush
iptables --table nat --flush
iptables --delete-chain
iptables --table nat --delete-chain
iptables --table nat --append POSTROUTING --out-interface $out -j MASQUERADE
iptables --append FORWARD --in-interface $int -j ACCEPT
iptables -P FORWARD ACCEPT

sysctl -w net.ipv4.ip_forward=1

#start hostapd
systemctl start hostapd
